version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install --save-dev @angular-devkit/build-angular
      - npm install
  build:
    commands:
      - ng b --prod --aot=false --build-optimizer=false
  post_build:
    commands:
      - aws s3 sync dist/ s3://aws-angular-s3 --delete
